<?php

/**
 * @file
 * Primary module hooks for custom_content_tools module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function custom_content_tools_theme(): array
{
  return [
    'content_item' => [
      'render element' => 'elements'
    ],
    'latest_content_items_block' => [
      'variables' => [
        'items' => [],
      ],
      'template' => 'latest-content-items-block',
    ],
  ];
}

/**
 * Prepares variables for content item templates.
 *
 * Default template: content-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content item information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_item(array &$variables): void
{
  /** @var Drupal\custom_content_tools\Entity\ContentItem  created_time*/
  $current_item = $variables['elements']['#content_item'];
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Add a "New" badge for items from the last 7 days
  $created_time = $current_item->get('created')->value;
  if ($created_time <= 7 * 24 * 60 * 60) {
    $variables['is_new'] = TRUE;
  } else {
    $variables['is_new'] = FALSE;
  }
}

/**
 * Implements hook_user_cancel().
 */
function custom_content_tools_user_cancel($edit, UserInterface $account, $method): void
{
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish content items.
      $storage = \Drupal::entityTypeManager()->getStorage('content_item');
      $content_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_item_ids) as $content_item) {
        $content_item->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize content items.
      $storage = \Drupal::entityTypeManager()->getStorage('content_item');
      $content_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_item_ids) as $content_item) {
        $content_item->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function custom_content_tools_user_predelete(UserInterface $account): void
{
  // Delete content items that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('content_item');
  $content_item_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($content_item_ids)
  );
  // Delete old revisions.
  $content_item_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($content_item_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}